### ISSUE TITLE
Windows 11: D2BS is not responding... starting profile loop

### ISSUE THREAD

**Issue by tapakahxp** [blizzhackers/kolbot#370]
Hello, is it possible to run KolBot on Windows 10 or 11 ?

After starting profile kolbot goes to infinity loop with "D2BS is not responding... starting profile" message.
Compatability mode (Windows 98/XP/7) in *.exe properties has no effect.

![Untitled](https://github.com/blizzhackers/kolbot/assets/66036789/05411a76-20e6-4d63-9d72-c26a3e0748e7)

**Comment by theBGuy** [comment]
This has been addressed so many times. Look through past issues, you likely didn't install the pre-reqs or your installed the incorrect ones. Either way closing this out.

**Comment by tapakahxp** [comment]
> This has been addressed so many times.

And there is still no solution
I've followed all stepes and still cant start it. It worked fine on Windows 7 before i migrated to Windows 11.
Can you post me an exact step i did wrong ?

> update D2BS to latest version.

It latest version from this repository.

> check the installed MS dependencies (VC++ 2005, 2008)

Checked. It installed and works fine.

> NET Framework 3.5, 4 or higher installed

It comes with Windows 11

> you can get this error and several crashes when there are differences between ...\d2bs\d2bs.ini and ...\data\profile.json. 

It's "clean" Kolbot install with only one test profile.
Works fine on Windows 7 from the same directory.

> run D2Bot.exe in Windows 7 Compatibility Mode + Administrator Mode

Stil no luck.


![Untitled](https://github.com/blizzhackers/kolbot/assets/66036789/5cca6103-92f9-49ab-adb0-056f43fb8527)
